# Generated by Django 6.1 on 2026-08-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Define el orden en el que aparecerá en el menú (ej. 1, 2, 3...)')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='gestion.marca')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_foto', models.ImageField(blank=True, null=True, upload_to='platos/fotos/')),
                ('archivo_ar_3d', models.FileField(blank=True, help_text='Sube aquí el archivo .gltf o .usdz para la Realidad Aumentada', null=True, upload_to='platos/ar_models/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='menu.categoria')),
            ],
        ),
    ]
