# Generated by Django 6.1 on 2026-08-17 17:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_activo', models.BooleanField(default=True, help_text='¿Este plato se está vendiendo en esta sucursal hoy?')),
                ('precio_local', models.DecimalField(decimal_places=2, help_text='Precio específico para esta sucursal (puede variar de la base)', max_digits=10)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='menu.plato')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='gestion.sucursal')),
            ],
            options={
                'verbose_name': 'Disponibilidad en Sucursal',
                'verbose_name_plural': 'Disponibilidad en Sucursales',
                'unique_together': {('sucursal', 'plato')},
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: Mesa 5, VIP 1, Terraza', max_length=50)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='gestion.sucursal')),
            ],
            options={
                'unique_together': {('sucursal', 'identificador')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PREPARACION', 'En Preparación'), ('LISTO', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('PAGADO', 'Pagado')], default='RECIBIDO', max_length=50)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='operaciones.mesa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_tomados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('notas_clientes', models.TextField(blank=True, help_text='Ej: Sin cebolla, extra salsa')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='operaciones.disponibilidadsucursal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='operaciones.pedido')),
            ],
        ),
    ]
