# Generated by Django 6.1 on 2026-09-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='qrs_mesas/'),
        ),
    ]
